# apply-callai-govtask-patch.ps1
# call-ai.js에 GOV_TASK 태그 파서(_handleGovTaskTags)를 추가하고
# 호출부에 등록한다. Base64+BOM 방식.

$ErrorActionPreference = 'Stop'
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}
function _b64d($s) { [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($s)) }
$path = ".\src\gopang\ai\call-ai.js"
if (-not (Test-Path $path)) { throw "call-ai.js를 찾을 수 없습니다 — 리포 루트에서 실행하세요(경로: src\gopang\ai\call-ai.js)." }
$encRead  = [System.Text.Encoding]::UTF8
$encWrite = New-Object System.Text.UTF8Encoding($true)
$content = [System.IO.File]::ReadAllText((Resolve-Path $path), $encRead)
$backupPath = ".\call-ai.js.bak-$(Get-Date -Format yyyyMMdd-HHmmss)"
Copy-Item $path $backupPath
Write-Host "백업 생성: $backupPath"

$funcOldB64 = "ICB9CgogIHJldHVybiBmYWxzZTsKfQoKLyoqCiAqIF9idWlsZEZpcnN0Q29udGFjdENvbnRleHQ="
$funcNewB64 = "ICB9CgogIHJldHVybiBmYWxzZTsKfQoKLy8g4pSA4pSAIFtHT1ZfVEFTS19EUkFGVF9SRVFVRVNUXS9bR09WX1RBU0tfU1VCTUlUX1JFUVVFU1RdIO2DnOq3uCDsspjrpqwg4pSA4pSA4pSA4pSA4pSA4pSACi8vICgyMDI2LTA3LTEyIOyLoOyEpCkg4oCUIFNQLTEwX2twdWJsaWMgdjMuMTAgwqdSRVFVSVJFRC1ET0NVTUVOVFPqsIAg7ZSE66Gs7ZSE7Yq466GcCi8vIOyngOyLnO2VmOuKlCDshJzrpZjsoJHsiJgg7Z2Q66aE7J2EIOyLpOygnCDshJzrsoQg7JeU65Oc7Y+s7J247Yq4KHdvcmtlci5qczogL2dvdi90YXNrL3N1Ym1pdCwKLy8gL2dvdi90YXNrL3NjaGVtYS9kcmFmdCkg7Zi47Lac66GcIOyXsOqysO2VnOuLpC4gwqdHT1ZfVEFTS19SRVFVRVNUL1JFU1BPTlNF6rCACi8vIOy9lOuTnCDsl4bsnbQg7ZSE66Gs7ZSE7Yq47JeQ66eMIOyeiOuNmCDqsoPqs7wg64+Z7J287ZWcIOyLpO2MqCDtjKjthLTsnbQg67CY67O165CY7KeAIOyViuuPhOuhnQovLyDrp4zrk6Ag7Iuk7KCcIO2KuOumrOqxsC4gX2hhbmRsZVNQQXV0aG9yVGFnc+yZgCDrj5nsnbztlZjqsowgSy1Db21wb3NlL0stRGVsaXZlcgovLyDqsozsnbTtirgg7JeG7J20IOyWtOuKkCBTUOyXkOyEnOuToCDsspjrpqztlZzri6Qg4oCUIGtnb3YoU1AtMTAp6rCAIO2ZnOyEsSBzeXN0ZW3snbwg65WMCi8vIOuCmOyYpOuKlCDtg5zqt7jrnbwg67OE64+EIOqyjOydtO2KuOqwgCDtlYTsmpQg7JeG64ukLgpleHBvcnQgYXN5bmMgZnVuY3Rpb24gX2hhbmRsZUdvdlRhc2tUYWdzKGZ1bGxSZXBseSwgYnViYmxlLCBzZW5kRm4gPSBjYWxsQUksIHVzZXJUZXh0ID0gJycpIHsKICBjb25zdCBfdXBkYXRlQnViYmxlID0gYXN5bmMgKHRleHQpID0+IHsKICAgIGlmICghYnViYmxlKSByZXR1cm47CiAgICBjb25zdCB7IF91cGRhdGVTdHJlYW1CdWJibGU6IF91c2IgfSA9IGF3YWl0IGltcG9ydCgnLi4vdWkvYnViYmxlLmpzJykuY2F0Y2goKCkgPT4gKHt9KSk7CiAgICBpZiAoX3VzYikgX3VzYihidWJibGUsIHRleHQpOwogIH07CgogIGNvbnN0IGdvdlRhc2tEcmFmdE1hdGNoID0gZnVsbFJlcGx5Lm1hdGNoKAogICAgL1xbR09WX1RBU0tfRFJBRlRfUkVRVUVTVFxdKFtcc1xTXSo/KVxbXC9HT1ZfVEFTS19EUkFGVF9SRVFVRVNUXF0vKTsKICBpZiAoZ292VGFza0RyYWZ0TWF0Y2gpIHsKICAgIGNvbnNvbGUubG9nKCdbR292VGFza10gR09WX1RBU0tfRFJBRlRfUkVRVUVTVCDqsJDsp4Ag4oCUIC9nb3YvdGFzay9zY2hlbWEvZHJhZnQg7Zi47LacJyk7CiAgICBhd2FpdCBfdXBkYXRlQnViYmxlKF9zdHJpcEludGVybmFsVGFncyhmdWxsUmVwbHkpKTsKICAgIGxldCBwYXlsb2FkID0gbnVsbDsKICAgIHRyeSB7CiAgICAgIHBheWxvYWQgPSBKU09OLnBhcnNlKGdvdlRhc2tEcmFmdE1hdGNoWzFdLnRyaW0oKSk7CiAgICB9IGNhdGNoIChlKSB7CiAgICAgIGF3YWl0IHNlbmRGbihgW0lOVEVSTkFMOiBHT1ZfVEFTS19EUkFGVF9SRVFVRVNU7J2YIEpTT04g7YyM7IuxIOyLpO2MqCgke2UubWVzc2FnZX0pIOKAlCBgICsKICAgICAgICBg7ZiV7Iud7J2EIOunnuy2sCDsnqzsi5zrj4TtlZjqsbDrgpgsIOyggOyepSDsl4bsnbQg7KGw7IKsIOuCtOyaqeunjCDsgqzsmqnsnpDsl5Dqsowg7YWN7Iqk7Yq466GcIOyViOuCtO2VmOqzoCBgICsKICAgICAgICBgIuyCrOuejCDqsoDthqAg7KCE7J206528IOuLpOuluCDsgqzsmqnsnpDsl5DqsozripQg6rO17Jyg65CY7KeAIOyViuuKlCDsnoTsi5wg7KCV67O0IuudvOuKlCDsoJDsnYQg67Cd7Z6I7IS47JqULl1gKTsKICAgICAgcmV0dXJuIHRydWU7CiAgICB9CiAgICBjb25zdCBiYXNlID0gKENGRy5lbmRwb2ludCB8fCAnJykucmVwbGFjZSgvXC8rJC8sICcnKTsKICAgIHRyeSB7CiAgICAgIGNvbnN0IHJlcyAgPSBhd2FpdCBmZXRjaChgJHtiYXNlfS9nb3YvdGFzay9zY2hlbWEvZHJhZnRgLCB7CiAgICAgICAgbWV0aG9kOiAnUE9TVCcsCiAgICAgICAgaGVhZGVyczogeyAnQ29udGVudC1UeXBlJzogJ2FwcGxpY2F0aW9uL2pzb24nIH0sCiAgICAgICAgYm9keTogSlNPTi5zdHJpbmdpZnkoeyAuLi5wYXlsb2FkLCBndWlkOiBfVVNFUj8uaXB2NiB8fCBVU0VSX0dVSUQgfHwgbnVsbCB9KSwKICAgICAgfSk7CiAgICAgIGNvbnN0IGRhdGEgPSBhd2FpdCByZXMuanNvbigpLmNhdGNoKCgpID0+IG51bGwpOwogICAgICBhd2FpdCBzZW5kRm4oYFtJTlRFUk5BTDogR09WX1RBU0tfRFJBRlRfUkVRVUVTVCDqsrDqs7wg7IiY7IugIOKAlCDsnbQg6rKw6rO866W8IOuwlO2DleycvOuhnCBgICsKICAgICAgICBgwqdSRVFVSVJFRC1ET0NVTUVOVFMgM+uLqOqzhCDsp4Dsi5wodmVyaWZpZWQg7Jes67aA7JeQIOuUsOuluCDqsr3qs6Ag66y46rWsIO2PrO2VqCnrjIDroZwgYCArCiAgICAgICAgYOyCrOyaqeyekOyXkOqyjCDsnpDsl7DsiqTrn73qsowg7JWI64K07ZWY7IS47JqUOiAke0pTT04uc3RyaW5naWZ5KGRhdGEpfV1gKTsKICAgIH0gY2F0Y2ggKGUpIHsKICAgICAgYXdhaXQgc2VuZEZuKGBbSU5URVJOQUw6IEdPVl9UQVNLX0RSQUZUX1JFUVVFU1Qg7ISc67KEIO2YuOy2nCDsi6TtjKgoJHtlLm1lc3NhZ2V9KSDigJQgYCArCiAgICAgICAgYOyggOyepeydtCDslYgg65CQ7J2M7J2EIOyCrOyaqeyekOyXkOqyjCDslYzrpqzqs6AsIOyngOq4iCDsobDsgqztlZwg64K07Jqp7J2AIOydtOuyiCDrjIDtmZTsl5DshJzrp4wgYCArCiAgICAgICAgYOycoO2aqO2VnCDsnoTsi5wg7JWI64K07J6E7J2EIOuqhe2Zle2eiCDtlZjshLjsmpQuXWApOwogICAgfQogICAgcmV0dXJuIHRydWU7CiAgfQoKICBjb25zdCBnb3ZUYXNrU3VibWl0TWF0Y2ggPSBmdWxsUmVwbHkubWF0Y2goCiAgICAvXFtHT1ZfVEFTS19TVUJNSVRfUkVRVUVTVFxdKFtcc1xTXSo/KVxbXC9HT1ZfVEFTS19TVUJNSVRfUkVRVUVTVFxdLyk7CiAgaWYgKGdvdlRhc2tTdWJtaXRNYXRjaCkgewogICAgY29uc29sZS5sb2coJ1tHb3ZUYXNrXSBHT1ZfVEFTS19TVUJNSVRfUkVRVUVTVCDqsJDsp4Ag4oCUIC9nb3YvdGFzay9zdWJtaXQg7Zi47LacJyk7CiAgICBhd2FpdCBfdXBkYXRlQnViYmxlKF9zdHJpcEludGVybmFsVGFncyhmdWxsUmVwbHkpKTsKICAgIGxldCBwYXlsb2FkID0gbnVsbDsKICAgIHRyeSB7CiAgICAgIHBheWxvYWQgPSBKU09OLnBhcnNlKGdvdlRhc2tTdWJtaXRNYXRjaFsxXS50cmltKCkpOwogICAgfSBjYXRjaCAoZSkgewogICAgICBhd2FpdCBzZW5kRm4oYFtJTlRFUk5BTDogR09WX1RBU0tfU1VCTUlUX1JFUVVFU1TsnZggSlNPTiDtjIzsi7Eg7Iuk7YyoKCR7ZS5tZXNzYWdlfSkg4oCUIGAgKwogICAgICAgIGDtmJXsi53snYQg66ee7LawIOyerOyLnOuPhO2VmOyEuOyalC4g7KCR7IiY64qUIOuQmOyngCDslYrslZjsirXri4jri6QuXWApOwogICAgICByZXR1cm4gdHJ1ZTsKICAgIH0KICAgIGNvbnN0IGJhc2UgPSAoQ0ZHLmVuZHBvaW50IHx8ICcnKS5yZXBsYWNlKC9cLyskLywgJycpOwogICAgdHJ5IHsKICAgICAgY29uc3QgcmVzICA9IGF3YWl0IGZldGNoKGAke2Jhc2V9L2dvdi90YXNrL3N1Ym1pdGAsIHsKICAgICAgICBtZXRob2Q6ICdQT1NUJywKICAgICAgICBoZWFkZXJzOiB7ICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRpb24vanNvbicgfSwKICAgICAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7IC4uLnBheWxvYWQsIGd1aWQ6IF9VU0VSPy5pcHY2IHx8IFVTRVJfR1VJRCB8fCBudWxsIH0pLAogICAgICB9KTsKICAgICAgY29uc3QgZGF0YSA9IGF3YWl0IHJlcy5qc29uKCkuY2F0Y2goKCkgPT4gbnVsbCk7CiAgICAgIGF3YWl0IHNlbmRGbihgW0lOVEVSTkFMOiBHT1ZfVEFTS19TVUJNSVRfUkVRVUVTVCDqsrDqs7wg7IiY7IugIOKAlCByZWNlaXB0X25v7JmAIGRpc2NsYWltZXIsIGAgKwogICAgICAgIGBzY2hlbWFfdmVyaWZpZWQg7ZWE65Oc64qUIOygiOuMgCDsmpTslb3Ct+yDneuete2VmOyngCDrp5Dqs6Ag6re4IOydmOuvuOulvCDsmKjsoITtnogg7IKs7Jqp7J6Q7JeQ6rKMIOyghOuLrO2VmOyEuOyalCBgICsKICAgICAgICBgKMKn7KCR7IiY67KI7Zi4IOuptOyxheusuOq1rCDssLjsobApOiAke0pTT04uc3RyaW5naWZ5KGRhdGEpfV1gKTsKICAgIH0gY2F0Y2ggKGUpIHsKICAgICAgYXdhaXQgc2VuZEZuKGBbSU5URVJOQUw6IEdPVl9UQVNLX1NVQk1JVF9SRVFVRVNUIOyEnOuyhCDtmLjstpwg7Iuk7YyoKCR7ZS5tZXNzYWdlfSkg4oCUIGAgKwogICAgICAgIGDsoJHsiJjqsIAg7Iuk7KCc66GcIOydtOujqOyWtOyngOyngCDslYrslZjsnYzsnYQg7IKs7Jqp7J6Q7JeQ6rKMIOuqhe2Zle2eiCDslYzrpqzshLjsmpQuIGAgKwogICAgICAgIGAi7KCR7IiY7ZaI7Iq164uI64ukIuudvOqzoCDrp5DtlZjrqbQg7JWIIOuQqeuLiOuLpC5dYCk7CiAgICB9CiAgICByZXR1cm4gdHJ1ZTsKICB9CgogIHJldHVybiBmYWxzZTsKfQoKLyoqCiAqIF9idWlsZEZpcnN0Q29udGFjdENvbnRleHQKCi8qKgogKiBfYnVpbGRGaXJzdENvbnRhY3RDb250ZXh0"
$callOldB64 = "ICAgIGNvbnN0IF9zcEF1dGhvckhhbmRsZWQgPSBhd2FpdCBfaGFuZGxlU1BBdXRob3JUYWdzKGZ1bGxSZXBseSwgYnViYmxlLCBjYWxsQUksIHVzZXJUZXh0KTsKICAgIGlmIChfc3BBdXRob3JIYW5kbGVkKSByZXR1cm47Cg=="
$callNewB64 = "ICAgIGNvbnN0IF9zcEF1dGhvckhhbmRsZWQgPSBhd2FpdCBfaGFuZGxlU1BBdXRob3JUYWdzKGZ1bGxSZXBseSwgYnViYmxlLCBjYWxsQUksIHVzZXJUZXh0KTsKICAgIGlmIChfc3BBdXRob3JIYW5kbGVkKSByZXR1cm47CgogICAgLy8g4pSA4pSAIEdPVl9UQVNLIO2DnOq3uCDsspjrpqwgKDIwMjYtMDctMTIg7Iug7ISkKSDilIDilIAKICAgIC8vIEstQ29tcG9zZS9LLURlbGl2ZXIg6rKM7J207Yq4IOyXhuydtCDslrTripAgU1Dsl5DshJzrk6Aoa2dvdi9TUC0xMCDtmZzshLHtmZTrkJwKICAgIC8vIOuMgO2ZlOyXkOyEnOunjCDsi6TsoJwg7Lac66Cl65CY64qUIO2DnOq3uOudvCDqsozsnbTtirjqsIAg67aI7ZWE7JqUKSDsspjrpqwg4oCUCiAgICAvLyBfaGFuZGxlU1BBdXRob3JUYWdzIOuwlOuhnCDri6TsnYwg7JyE7LmYLgogICAgY29uc3QgX2dvdlRhc2tIYW5kbGVkID0gYXdhaXQgX2hhbmRsZUdvdlRhc2tUYWdzKGZ1bGxSZXBseSwgYnViYmxlLCBjYWxsQUksIHVzZXJUZXh0KTsKICAgIGlmIChfZ292VGFza0hhbmRsZWQpIHJldHVybjsK"

$funcOld = _b64d $funcOldB64
$funcNew = _b64d $funcNewB64
$callOld = _b64d $callOldB64
$callNew = _b64d $callNewB64

if ($funcOld -notmatch 'return false') { throw 'Base64 디코딩 결과 이상 — PowerShell 버전을 확인하세요.' }

$replacements = @(
  @{ Name = '_handleGovTaskTags 함수 정의 삽입'; Old = $funcOld; New = $funcNew },
  @{ Name = '호출부 등록(_spAuthorHandled 다음)'; Old = $callOld; New = $callNew }
)
$applied = 0
foreach ($r in $replacements) {
  if ($content.Contains($r.Old)) {
    $content = $content.Replace($r.Old, $r.New)
    Write-Host "✅ $($r.Name) 치환 완료"
    $applied++
  } else {
    Write-Warning "⚠️ $($r.Name) — 원본과 일치하는 블록을 못 찾았습니다."
  }
}
if ($applied -gt 0) {
  [System.IO.File]::WriteAllText((Resolve-Path $path), $content, $encWrite)
  Write-Host "`ncall-ai.js 저장 완료 (${applied}/2 블록 치환됨)"
} else {
  Write-Host "`n치환된 블록이 없어 파일을 다시 쓰지 않았습니다."
}
Write-Host "`n확인(Node.js 있는 경우): Copy-Item src\gopang\ai\call-ai.js $env:TEMP\ca-check.mjs; node --check $env:TEMP\ca-check.mjs"
