// division-tables.js
// 과/팀(division) 단위 키워드 라우팅 테이블 — 2026-08-02 재구현
// (직전 세션에서 fix/sp-tree-citizen-routing-gaps 브랜치에 구축 중이던 작업이 push 전
//  크레딧 소진으로 유실되어, prompts/gov-tree/{02-do-dept,04-city}/divisions/ 산하
//  SP 파일들(§0 상위상속 헤더 + §1 정체성 문단)을 다시 파싱해 재생성했다.)
//
// 각 항목: code(SP 코드), 국코드/도메인(상위 부서), 시코드(city만),
// name(과/팀 한글명), desc(LLM 폴백 후보 설명용 — §1 정체성 발췌),
// kw(키워드 매칭용 — 과/팀명 자체 + 정체성 문단에서 추출한 소관 업무 어절),
// file(해당 과/팀 SP 원문 경로, _fetchText 인자로 그대로 사용 가능)

export const CITY_DIVISION_TABLE = [
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-ENVGUIDE", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 환경지도과", desc: "당신은 **제주시청 청정환경국 환경지도과**를 대표하는 AI 레이어다. 환경오염 단속, 폐기물 배출업소 지도·점검을 담당한다.",
    kw: ["점검", "폐기물 배출업소 지도", "환경오염 단속", "환경지도", "환경지도과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-ENVGUIDE_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-ENVMGMT", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 환경관리과", desc: "당신은 **제주시청 청정환경국 환경관리과**를 대표하는 AI 레이어다. 환경 총괄, 대기·수질 관리를 담당한다 — 도청 기후환경국(SP-DO-CLIMATE)이 도 전체 환경정책·탄소중립을 다루는 것과 달리, 이 과는 관내 환경 인허가·관리 실무를 집행한다.",
    kw: ["대기", "수질 관리", "환경 총괄", "환경관리", "환경관리과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-ENVMGMT_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-FACILITY", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 환경시설관리소", desc: "당신은 **제주시청 청정환경국 환경시설관리소**를 대표하는 AI 레이어다. 생활폐기물 소각·매립시설 운영을 담당한다.",
    kw: ["매립시설 운영", "폐기물 소각", "환경시설", "환경시설관리소"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-FACILITY_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-JEOLMUL", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 절물생태관리소", desc: "당신은 **제주시청 청정환경국 절물생태관리소**를 대표하는 AI 레이어다. 절물자연휴양림 운영·관리를 담당한다.",
    kw: ["관리", "절물생태", "절물생태관리소", "절물자연휴양림 운영"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-JEOLMUL_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-LIVINGENV", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 생활환경과", desc: "당신은 **제주시청 청정환경국 생활환경과**를 대표하는 AI 레이어다. 생활폐기물 수거, 재활용 정책을 담당한다.",
    kw: ["생활환경", "생활환경과", "재활용 정책", "폐기물 수거"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-LIVINGENV_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-PARKS", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 공원녹지과", desc: "당신은 **제주시청 청정환경국 공원녹지과**를 대표하는 AI 레이어다. 도시공원·가로수 관리를 담당한다.",
    kw: ["가로수 관리", "공원녹지", "공원녹지과", "도시공원"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-PARKS_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-ARTCENTER", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 제주아트센터", desc: "당신은 **제주시청 문화관광체육국 제주아트센터**를 대표하는 AI 레이어다. 제주아트센터 공연장 운영·대관을 담당한다.",
    kw: ["대관", "제주아트", "제주아트센터", "제주아트센터 공연장 운영"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-ARTCENTER_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-ART", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 문화예술과", desc: "당신은 **제주시청 문화관광체육국 문화예술과**를 대표하는 AI 레이어다. 문화예술 지원사업, 공연·전시 행정을 담당한다.",
    kw: ["공연", "문화예술", "문화예술 지원사업", "문화예술과", "전시 행정"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-ART_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-SPORTS", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 체육진흥과", desc: "당신은 **제주시청 문화관광체육국 체육진흥과**를 대표하는 AI 레이어다. 생활체육 진흥, 공공체육시설 관리를 담당한다.",
    kw: ["공공체육시설 관리", "체육 진흥", "체육진흥", "체육진흥과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-SPORTS_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-TAMNALIB", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 탐라도서관", desc: "당신은 **제주시청 문화관광체육국 탐라도서관**를 대표하는 AI 레이어다. 제주시립 탐라도서관 — 도서 대출·반납, 자료실 이용을 담당하는 공공도서관이다.",
    kw: ["제주시립 탐라도서관", "탐라도서관"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-TAMNALIB_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-TOURISM", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 관광진흥과", desc: "당신은 **제주시청 문화관광체육국 관광진흥과**를 대표하는 AI 레이어다. 관광사업체 등록, 관광안내소 운영을 담당한다 — 도청 관광교류국(SP-DO-TOURISM)이 도 전체 관광정책·해외마케팅을 다루는 것과 달리, 이 과는 관내 관광사업체 개별 등록·안내소 운영 실무를 담당한다.",
    kw: ["관광사업체 등록", "관광안내소 운영", "관광진흥", "관광진흥과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-TOURISM_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-UDANGLIB", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 우당도서관", desc: "당신은 **제주시청 문화관광체육국 우당도서관**를 대표하는 AI 레이어다. 제주시립 우당도서관 — 도서 대출·반납, 자료실 이용을 담당하는 공공도서관이다.",
    kw: ["우당도서관", "제주시립 우당도서관"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-UDANGLIB_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-ECON-INFOSUPPORT", 국코드: "econ", 시코드: "jejusi",
    name: "제주시청 경제일자리국 정보화지원과", desc: "당신은 **제주시청 경제일자리국 정보화지원과**를 대표하는 AI 레이어다. 정보화교육, 스마트시티 관련 사업을 담당한다.",
    kw: ["스마트시티 관련 사업", "정보화교육", "정보화지원", "정보화지원과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-ECON-INFOSUPPORT_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-ECON-JOBENERGY", 국코드: "econ", 시코드: "jejusi",
    name: "제주시청 경제일자리국 일자리에너지과", desc: "당신은 **제주시청 경제일자리국 일자리에너지과**를 대표하는 AI 레이어다. 공공일자리사업, 에너지 절약·신재생에너지 보급 지원을 담당한다.",
    kw: ["공공일자리사업", "신재생에너지 보급 지원", "에너지 절약", "일자리에너지", "일자리에너지과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-ECON-JOBENERGY_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-ECON-SMB", 국코드: "econ", 시코드: "jejusi",
    name: "제주시청 경제일자리국 경제소상공인과", desc: "당신은 **제주시청 경제일자리국 경제소상공인과**를 대표하는 AI 레이어다. 소상공인 지원, 전통시장 활성화를 담당한다 — 도청 경제활력국(SP-DO-ECON)이 도 전체 산업정책을 다루는 것과 달리, 이 과는 제주시 관내 소상공인 개별 지원사업을 집행한다.",
    kw: ["경제소상공인", "경제소상공인과", "소상공인 지원", "전통시장 활성화"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-ECON-SMB_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-ECON-VILLAGE", 국코드: "econ", 시코드: "jejusi",
    name: "제주시청 경제일자리국 마을활력과", desc: "당신은 **제주시청 경제일자리국 마을활력과**를 대표하는 AI 레이어다. 마을만들기, 주민 주도 도시재생 사업을 담당한다 — 자치행정과(SELFGOV)의 '읍면동 행정 총괄·주민자치'와 이름이 유사해 보이지만, 이 과는 마을 단위 물리적·경제적 활력사업(마을기업, 도시재생 등)을 집행하고 자치행정과는 읍면동 행정지원·주민자치위원회 운영을 담당한다는 점에서 ",
    kw: ["마을만들기", "마을활력", "마을활력과", "주민 주도 도시재생 사업"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-ECON-VILLAGE_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-BASICGOVPREP", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 기초자치단체 설치준비지원단", desc: "당신은 **제주시청 자치행정국 기초자치단체 설치준비지원단**을 대표하는 AI 레이어다.",
    kw: ["설치준비지원단"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-BASICGOVPREP_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-BUDGET", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 기획예산과", desc: "당신은 **제주시청 자치행정국 기획예산과**를 대표하는 AI 레이어다. 시정 전반의 기획·예산편성·조직관리를 담당하며, 도청 기획조정실(SP-DO-PLAN)의 시청 축소판에 가깝다 — 단, 시는 독자 예산편성권이 도 예산틀 안에 있어 도청과 관계가 더 밀접하다.",
    kw: ["기획예산", "기획예산과", "시정 전반의 기획", "예산편성", "조직관리를 담당하며"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-BUDGET_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-GENERAL", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 총무과", desc: "당신은 **제주시청 자치행정국 총무과**를 대표하는 AI 레이어다. 도청 실·국 계층의 총무과(예: SP-DIV-JACHI-GENERAL)와 성격이 유사하다 — 시민을 직접 상대하기보다 시청 내부 행정(문서·인사·의전·청사관리)을 지원한다.",
    kw: ["국 계층의 총무과와 성격이 유사하다", "도청 실", "총무", "총무과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-GENERAL_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-PROPERTYTAX", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 재산세과", desc: "당신은 **제주시청 자치행정국 재산세과**를 대표하는 AI 레이어다. 재산세·자동차세 등 시청이 매년 정기적으로 부과(고지)하는 지방세를 담당한다 — **취득·등록 시 신고하는 세목(취득세 등)은 세무과 소관이므로 혼동하지 않는다.**",
    kw: ["재산세", "재산세과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-PROPERTYTAX_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-SELFGOV", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 자치행정과", desc: "당신은 **제주시청 자치행정국 자치행정과**를 대표하는 AI 레이어다. 읍면동 행정 총괄·지원, 주민자치·마을공동체 관련 업무, 선거 관련 행정지원(선거관리위원회와는 별개 기관)을 담당한다.",
    kw: ["마을공동체 관련 업무", "선거 관련 행정지원", "읍면동 행정 총괄", "자치행정", "자치행정과", "주민자치", "지원"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-SELFGOV_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-TAX", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 세무과", desc: "당신은 **제주시청 자치행정국 세무과**를 대표하는 AI 레이어다. 취득세·등록면허세·지방소득세 등 신고납부형 지방세를 담당한다 — **재산세·자동차세 등 부과형 지방세는 재산세과(별도 과) 소관이므로 혼동하지 않는다.**",
    kw: ["등록면허세", "세무", "세무과", "지방소득세 등 신고납부형 지방세", "취득세"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-TAX_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-SAFETY-GENERAL", 국코드: "safety", 시코드: "jejusi",
    name: "제주시청 안전교통국 안전총괄과", desc: "당신은 **제주시청 안전교통국 안전총괄과**를 대표하는 AI 레이어다. 재난안전대책본부 운영, 민방위, 자연·사회재난 대응을 총괄한다 — 도청 도민안전건강실(SP-DO-SAFETY)이 도 전체 재난정책을 다루는 것과 달리, 이 과는 제주시 관내 현장 대응·재난안전대책본부 실무를 담당한다.",
    kw: ["민방위", "사회재난 대응을 총괄한다", "안전총괄", "안전총괄과", "자연", "재난안전대책본부 운영"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-SAFETY-GENERAL_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-SAFETY-TRAFFIC", 국코드: "safety", 시코드: "jejusi",
    name: "제주시청 안전교통국 교통행정과", desc: "당신은 **제주시청 안전교통국 교통행정과**를 대표하는 AI 레이어다. 제주시 관내 시내버스·택시 등 여객자동차운송사업 인허가, 교통안전시설물(신호등·표지판) 관리 실무를 담당한다 — 도청 교통항공국(SP-DO-TRANSPORT)이 도 전체 대중교통 정책·요금체계를 다루는 것과 달리, 이 과는 관내 개별 인허가·시설 실무를 처리한다.",
    kw: ["교통안전시설물 관리 실무", "교통행정", "교통행정과", "제주시 관내 시내버스", "택시 등 여객자동차운송사업 인허가"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-SAFETY-TRAFFIC_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-SAFETY-VEHICLE", 국코드: "safety", 시코드: "jejusi",
    name: "제주시청 안전교통국 차량관리과", desc: "당신은 **제주시청 안전교통국 차량관리과**를 대표하는 AI 레이어다. 자동차 등록·이전등록, 차고지증명제 운영을 담당한다.",
    kw: ["이전등록", "자동차 등록", "차고지증명제 운영", "차량관리", "차량관리과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-SAFETY-VEHICLE_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-BASICLIVELIHOOD", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 기초생활보장과", desc: "당신은 **제주시청 복지위생국 기초생활보장과**를 대표하는 AI 레이어다. 국민기초생활보장(생계·의료·주거·교육급여) 신청·조사를 담당한다.",
    kw: ["국민기초생활보장 신청", "기초생활보장", "기초생활보장과", "조사"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-BASICLIVELIHOOD_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-DISABLED", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 장애인복지과", desc: "당신은 **제주시청 복지위생국 장애인복지과**를 대표하는 AI 레이어다. 장애인 등록, 장애수당·장애인연금, 장애인 활동지원 신청을 담당한다.",
    kw: ["장애수당", "장애인 등록", "장애인 활동지원 신청", "장애인복지", "장애인복지과", "장애인연금"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-DISABLED_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-ELDERLY", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 노인복지과", desc: "당신은 **제주시청 복지위생국 노인복지과**를 대표하는 AI 레이어다. 기초연금, 노인일자리, 경로당 지원을 담당한다.",
    kw: ["경로당 지원", "기초연금", "노인복지", "노인복지과", "노인일자리"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-ELDERLY_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-HYGIENE", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 위생관리과", desc: "당신은 **제주시청 복지위생국 위생관리과**를 대표하는 AI 레이어다. 식품위생업소(음식점 등) 및 공중위생업(숙박·미용 등) 인허가·신고를 담당한다.",
    kw: ["공중위생업 인허가", "식품위생업소", "신고", "위생관리", "위생관리과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-HYGIENE_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-RESIDENT", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 주민복지과", desc: "당신은 **제주시청 복지위생국 주민복지과**를 대표하는 AI 레이어다. 복지 총괄·긴급복지지원·사회보장급여 총괄 조정을 담당한다 — 도청 복지가족국(SP-DO-WELFARE)이 도 전체 복지정책을 수립하는 것과 달리, 이 과는 제주시 관내 개별 신청·급여 실행을 담당한다.",
    kw: ["긴급복지지원", "복지 총괄", "사회보장급여 총괄 조정", "주민복지", "주민복지과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-RESIDENT_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-WOMENFAMILY", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 여성가족과", desc: "당신은 **제주시청 복지위생국 여성가족과**를 대표하는 AI 레이어다. 한부모가족 지원, 가정폭력·성폭력 피해자 보호, 여성긴급전화 연계를 담당한다.",
    kw: ["가정폭력", "성폭력 피해자 보호", "여성가족", "여성가족과", "여성긴급전화 연계", "한부모가족 지원"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-WOMENFAMILY_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-CITRUS", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 감귤유통과", desc: "당신은 **서귀포시청 농수축산경제국 감귤유통과**를 대표하는 AI 레이어다. 감귤 유통·가격안정, 감귤 관련 조례 집행을 담당한다 — 제주 감귤 산업 특성상 이 과는 서귀포시(제주 최대 감귤 주산지)에만 있는 특화 부서로 확인된다.",
    kw: ["가격안정", "감귤 관련 조례 집행", "감귤 유통", "감귤유통", "감귤유통과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-CITRUS_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-DIGITAL", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 디지털혁신과", desc: "당신은 **서귀포시청 농수축산경제국 디지털혁신과**를 대표하는 AI 레이어다. 지역 디지털 전환·정보화 지원을 담당한다 — 제주시 정보화지원과(경제일자리국 산하)에 대응하는 서귀포시 부서로 추정된다.",
    kw: ["디지털혁신", "디지털혁신과", "정보화 지원", "지역 디지털 전환"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-DIGITAL_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-ECOFARM", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 친환경농정과", desc: "당신은 **서귀포시청 농수축산경제국 친환경농정과**를 대표하는 AI 레이어다. 친환경농업 인증·지원, 일반 농정을 담당한다.",
    kw: ["일반 농정", "지원", "친환경농업 인증", "친환경농정", "친환경농정과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-ECOFARM_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-FISHERY", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 해양수산과", desc: "당신은 **서귀포시청 농수축산경제국 해양수산과**를 대표하는 AI 레이어다. 어업 면허·허가, 수산물 유통을 담당한다 — 도청 해양수산국(SP-DO-OCEAN)이 도 전체 어업 정책·국가관리항만을 다루는 것과 달리, 이 과는 관내 개별 어업면허·수산업 인허가를 담당한다.",
    kw: ["수산물 유통", "어업 면허", "해양수산", "해양수산과", "허가"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-FISHERY_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-JOBS", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 경제일자리과", desc: "당신은 **서귀포시청 농수축산경제국 경제일자리과**를 대표하는 AI 레이어다. 소상공인 지원, 일자리 정책을 담당한다 — 제주시의 경제소상공인과·일자리에너지과(경제일자리국 산하)에 해당하는 업무를 서귀포시는 이 국 안의 한 과가 통합 담당하는 것으로 확인된다.",
    kw: ["경제일자리", "경제일자리과", "소상공인 지원", "일자리 정책"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-JOBS_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-LIVESTOCK", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 청정축산과", desc: "당신은 **서귀포시청 농수축산경제국 청정축산과**를 대표하는 AI 레이어다. 축산업 허가·신고, 가축분뇨 관리, 동물방역을 담당한다.",
    kw: ["가축분뇨 관리", "동물방역", "신고", "청정축산", "청정축산과", "축산업 허가"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-LIVESTOCK_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CLIMATE-ENVMGMT", 국코드: "climate", 시코드: "seogwipo",
    name: "서귀포시청 청정환경국 기후환경과", desc: "당신은 **서귀포시청 청정환경국 기후환경과**를 대표하는 AI 레이어다. 환경 총괄, 대기·수질 관리, 기후 관련 인허가를 담당한다 — 제주시의 동명 국(局) 산하 환경관리과·환경지도과 2개 과 업무를 서귀포시는 이 과 하나가 통합 담당하는 것으로 추정된다.",
    kw: ["기후 관련 인허가", "기후환경", "기후환경과", "대기", "수질 관리", "환경 총괄"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CLIMATE-ENVMGMT_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CLIMATE-FORESTRECREATION", 국코드: "climate", 시코드: "seogwipo",
    name: "서귀포시청 청정환경국 산림휴양관리소", desc: "당신은 **서귀포시청 청정환경국 산림휴양관리소**를 대표하는 AI 레이어다. 서귀포시 관내 산림휴양시설(휴양림·숲길 등) 운영·관리를 담당한다 — 제주시 절물생태관리소(SP-CITYDIV-JEJUSI-CLIMATE-JEOLMUL)에 대응하는 서귀포시 시설이다.",
    kw: ["관리", "산림휴양", "산림휴양관리소", "서귀포시 관내 산림휴양시설 운영"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CLIMATE-FORESTRECREATION_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CLIMATE-LIVINGENV", 국코드: "climate", 시코드: "seogwipo",
    name: "서귀포시청 청정환경국 생활환경과", desc: "당신은 **서귀포시청 청정환경국 생활환경과**를 대표하는 AI 레이어다. 생활폐기물 수거, 재활용 정책을 담당한다.",
    kw: ["생활환경", "생활환경과", "재활용 정책", "폐기물 수거"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CLIMATE-LIVINGENV_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CLIMATE-PARKS", 국코드: "climate", 시코드: "seogwipo",
    name: "서귀포시청 청정환경국 공원녹지과", desc: "당신은 **서귀포시청 청정환경국 공원녹지과**를 대표하는 AI 레이어다. 도시공원·가로수 관리를 담당한다.",
    kw: ["가로수 관리", "공원녹지", "공원녹지과", "도시공원"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CLIMATE-PARKS_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-BUILDING", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 건축과", desc: "당신은 **서귀포시청 안전도시건설국 건축과**를 대표하는 AI 레이어다. 건축 인허가, 건축물 안전점검을 담당한다.",
    kw: ["건축", "건축 인허가", "건축과", "건축물 안전점검"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-BUILDING_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-CITY", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 도시과", desc: "당신은 **서귀포시청 안전도시건설국 도시과**를 대표하는 AI 레이어다. 도시계획, 도시재생 행정을 담당한다.",
    kw: ["도시", "도시계획", "도시과", "도시재생 행정"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-CITY_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-CONSTRUCT", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 건설과", desc: "당신은 **서귀포시청 안전도시건설국 건설과**를 대표하는 AI 레이어다. 도로·하천 등 토목시설 건설·관리를 담당한다.",
    kw: ["건설", "건설과", "관리", "도로", "하천 등 토목시설 건설"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-CONSTRUCT_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-GENERAL", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 안전총괄과", desc: "당신은 **서귀포시청 안전도시건설국 안전총괄과**를 대표하는 AI 레이어다. 재난안전대책본부 운영, 민방위, 자연·사회재난 대응을 총괄한다 — 제주시 안전교통국 안전총괄과(SP-CITYDIV-JEJUSI-SAFETY-GENERAL)에 대응하며, 도청 도민안전건강실(SP-DO-SAFETY)과는 정책 vs 현장 대응으로 구분된다.",
    kw: ["민방위", "사회재난 대응을 총괄한다", "안전총괄", "안전총괄과", "자연", "재난안전대책본부 운영"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-GENERAL_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-TRAFFIC", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 교통행정과", desc: "당신은 **서귀포시청 안전도시건설국 교통행정과**를 대표하는 AI 레이어다. 여객자동차운송사업 인허가, 교통안전시설물 관리를 담당한다 — 제주시 안전교통국 교통행정과(SP-CITYDIV-JEJUSI-SAFETY-TRAFFIC)에 대응하나, 서귀포시는 이 업무가 안전총괄과와 별개로 안전도시건설국 산하에 있다는 점에서 소속 국 구조가 제주시와 다르지 않다(둘 ",
    kw: ["교통안전시설물 관리", "교통행정", "교통행정과", "여객자동차운송사업 인허가"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-TRAFFIC_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-WATER", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 상하수도과", desc: "당신은 **서귀포시청 안전도시건설국 상하수도과**를 대표하는 AI 레이어다. 상수도·하수도 시설 관리, 급수·배수 민원을 담당한다.",
    kw: ["급수", "배수 민원", "상수도", "상하수도", "상하수도과", "하수도 시설 관리"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-WATER_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-ARTMUSEUM", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 서귀포 공립미술관", desc: "당신은 **서귀포시청 문화관광체육국 서귀포 공립미술관**를 대표하는 AI 레이어다. 서귀포시 공립미술관 운영·전시를 담당한다.",
    kw: ["공립미술관", "서귀포시 공립미술관 운영", "전시"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-ARTMUSEUM_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-ARTSHALL", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 서귀포예술의전당", desc: "당신은 **서귀포시청 문화관광체육국 서귀포예술의전당**를 대표하는 AI 레이어다. 서귀포예술의전당 공연장 운영·대관을 담당한다 — 제주시 제주아트센터(SP-CITYDIV-JEJUSI-CULTURE-ARTCENTER)에 대응하는 서귀포시 공연시설이다.",
    kw: ["대관", "서귀포예술의전당", "서귀포예술의전당 공연장 운영"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-ARTSHALL_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-ART", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 문화예술과", desc: "당신은 **서귀포시청 문화관광체육국 문화예술과**를 대표하는 AI 레이어다. 문화예술 지원사업 행정을 담당한다.",
    kw: ["문화예술", "문화예술 지원사업 행정", "문화예술과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-ART_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-LIBRARYMGMT", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 도서관운영사무소", desc: "당신은 **서귀포시청 문화관광체육국 도서관운영사무소**를 대표하는 AI 레이어다. 서귀포시 관내 공공도서관 운영을 총괄한다 — 제주시가 도서관마다 개별 부서(우당·탐라)로 관리하는 것과 달리, 서귀포시는 하나의 사무소가 여러 도서관을 총괄하는 구조로 확인된다(2026-07-13 시점, 개별 도서관명은 재확인 필요).",
    kw: ["도서관운영", "도서관운영사무소"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-LIBRARYMGMT_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-SPORTS", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 체육진흥과", desc: "당신은 **서귀포시청 문화관광체육국 체육진흥과**를 대표하는 AI 레이어다. 생활체육 진흥, 공공체육시설 관리를 담당한다.",
    kw: ["공공체육시설 관리", "체육 진흥", "체육진흥", "체육진흥과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-SPORTS_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-TOURISMFACILITY", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 관광지관리소", desc: "당신은 **서귀포시청 문화관광체육국 관광지관리소**를 대표하는 AI 레이어다. 서귀포시 관내 공공 관광지(전망대·공원형 관광지 등) 시설 관리를 담당한다.",
    kw: ["관광지", "관광지관리소", "서귀포시 관내 공공 관광지 시설 관리"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-TOURISMFACILITY_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-TOURISM", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 관광진흥과", desc: "당신은 **서귀포시청 문화관광체육국 관광진흥과**를 대표하는 AI 레이어다. 관광사업체 등록을 담당한다 — 도청 관광교류국(SP-DO-TOURISM)의 정책·해외마케팅과 구분된다.",
    kw: ["관광사업체 등록", "관광진흥", "관광진흥과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-TOURISM_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-HEALTH-ADMIN", 국코드: "health", 시코드: "seogwipo",
    name: "서귀포시청 서귀포보건소 보건행정과", desc: "당신은 **서귀포시청 서귀포보건소 보건행정과**를 대표하는 AI 레이어다. 보건소 행정 총괄, 의료기관 인허가를 담당한다.",
    kw: ["보건소 행정 총괄", "보건행정", "보건행정과", "의료기관 인허가"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-HEALTH-ADMIN_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-HEALTH-EASTCENTER", 국코드: "health", 시코드: "seogwipo",
    name: "서귀포시청 서귀포보건소 동부보건소", desc: "당신은 **서귀포시청 서귀포보건소 동부보건소**를 대표하는 AI 레이어다. 서귀포시 동부지역 관할 보건지소 — 예방접종·건강검진 등 보건소 기능을 지역 분산 수행한다.",
    kw: ["동부보건", "동부보건소", "서귀포시 동부지역 관할 보건지소"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-HEALTH-EASTCENTER_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-HEALTH-PROMOTION", 국코드: "health", 시코드: "seogwipo",
    name: "서귀포시청 서귀포보건소 건강증진과", desc: "당신은 **서귀포시청 서귀포보건소 건강증진과**를 대표하는 AI 레이어다. 예방접종, 건강검진, 만성질환 관리사업을 담당한다.",
    kw: ["건강검진", "건강증진", "건강증진과", "만성질환 관리사업", "예방접종"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-HEALTH-PROMOTION_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-HEALTH-WESTCENTER", 국코드: "health", 시코드: "seogwipo",
    name: "서귀포시청 서귀포보건소 서부보건소", desc: "당신은 **서귀포시청 서귀포보건소 서부보건소**를 대표하는 AI 레이어다. 서귀포시 서부지역 관할 보건지소 — 예방접종·건강검진 등 보건소 기능을 지역 분산 수행한다.",
    kw: ["서귀포시 서부지역 관할 보건지소", "서부보건", "서부보건소"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-HEALTH-WESTCENTER_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-BASICGOVPREP", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 기초자치단체설치준비지원단", desc: "당신은 **서귀포시청 자치행정국 기초자치단체설치준비지원단**를 대표하는 AI 레이어다. 기초자치단체(시·군 등 법인격 있는 기초지자체) 부활·도입 준비를 위해 설치됐다 — **제주시의 동일 명칭 부서(SP-CITYDIV-JEJUSI-JACHI-BASICGOVPREP)와 동일한 사정을 공유한다**: 민선9기 위성곤 도정이 기초자치단체 도입을 사실상 추진하지 ",
    kw: ["기초자치단체 부활", "기초자치단체설치준비지원단", "도입 준비를 위해 설치됐다"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-BASICGOVPREP_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-BUDGET", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 기획예산과", desc: "당신은 **서귀포시청 자치행정국 기획예산과**를 대표하는 AI 레이어다. 시정 기획·예산편성·조직관리를 담당한다.",
    kw: ["기획예산", "기획예산과", "시정 기획", "예산편성", "조직관리"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-BUDGET_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-GENERAL", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 총무과", desc: "당신은 **서귀포시청 자치행정국 총무과**를 대표하는 AI 레이어다. 일반서무·인사·의전·청사관리를 지원한다.",
    kw: ["의전", "인사", "일반서무", "청사관리를 지원한다", "총무", "총무과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-GENERAL_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-LIFELONGED", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 평생교육과", desc: "당신은 **서귀포시청 자치행정국 평생교육과**를 대표하는 AI 레이어다. 평생교육 프로그램, 도서관과 별개의 평생학습 정책을 담당한다 — 제주시 조직에는 이 명칭의 독립 과가 없어 서귀포시 고유 조직으로 확인된다.",
    kw: ["도서관과 별개의 평생학습 정책", "평생교육", "평생교육 프로그램", "평생교육과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-LIFELONGED_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-SELFGOV", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 자치행정과", desc: "당신은 **서귀포시청 자치행정국 자치행정과**를 대표하는 AI 레이어다. 읍면동 행정 총괄·지원, 선거 행정지원을 담당한다 — 제주시의 동명 부서(SP-CITYDIV-JEJUSI-JACHI-SELFGOV)와 달리, 서귀포시는 마을공동체·평생교육 업무가 별도 과(마을활력과·평생교육과)로 분리돼 있어 이 과의 업무 범위가 제주시보다 좁다는 점에 유의한다.",
    kw: ["선거 행정지원", "읍면동 행정 총괄", "자치행정", "자치행정과", "지원"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-SELFGOV_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-TAX", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 세무과", desc: "당신은 **서귀포시청 자치행정국 세무과**를 대표하는 AI 레이어다. 취득세·등록면허세 등 신고형 지방세를 담당한다 — 재산세·자동차세 등 부과형 지방세는 서귀포시의 경우 별도 재산세과가 city-dept-master-data.json에 없어, 세무과가 이를 함께 담당하는 것으로 추정된다(제주시와의 구조 차이 — 재검증 필요).",
    kw: ["등록면허세 등 신고형 지방세", "세무", "세무과", "취득세"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-TAX_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-VILLAGE", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 마을활력과", desc: "당신은 **서귀포시청 자치행정국 마을활력과**를 대표하는 AI 레이어다. 마을만들기, 주민 주도 마을공동체 사업을 담당한다 — **제주시와의 구조적 차이**: 제주시는 이 업무를 경제일자리국(SP-CITYDIV-JEJUSI-ECON-VILLAGE)이 담당하지만, 서귀포시는 자치행정국 산하에 있다. 같은 이름의 업무라도 두 시(市) 사이에 소속 국(局) 자체",
    kw: ["마을만들기", "마을활력", "마을활력과", "주민 주도 마을공동체 사업"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-VILLAGE_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-WELFARE-DISABLED", 국코드: "welfare", 시코드: "seogwipo",
    name: "서귀포시청 복지위생국 장애인복지과", desc: "당신은 **서귀포시청 복지위생국 장애인복지과**를 대표하는 AI 레이어다. 장애인 등록, 장애수당·장애인연금, 활동지원 신청을 담당한다.",
    kw: ["장애수당", "장애인 등록", "장애인복지", "장애인복지과", "장애인연금", "활동지원 신청"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-WELFARE-DISABLED_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-WELFARE-ELDERLY", 국코드: "welfare", 시코드: "seogwipo",
    name: "서귀포시청 복지위생국 노인복지과", desc: "당신은 **서귀포시청 복지위생국 노인복지과**를 대표하는 AI 레이어다. 기초연금, 노인일자리, 경로당 지원을 담당한다.",
    kw: ["경로당 지원", "기초연금", "노인복지", "노인복지과", "노인일자리"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-WELFARE-ELDERLY_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-WELFARE-HYGIENE", 국코드: "welfare", 시코드: "seogwipo",
    name: "서귀포시청 복지위생국 위생관리과", desc: "당신은 **서귀포시청 복지위생국 위생관리과**를 대표하는 AI 레이어다. 식품위생업(음식점 등) 및 공중위생업(숙박·미용 등) 인허가·신고를 담당한다.",
    kw: ["공중위생업 인허가", "식품위생업", "신고", "위생관리", "위생관리과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-WELFARE-HYGIENE_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-WELFARE-RESIDENT", 국코드: "welfare", 시코드: "seogwipo",
    name: "서귀포시청 복지위생국 주민복지과", desc: "당신은 **서귀포시청 복지위생국 주민복지과**를 대표하는 AI 레이어다. 복지 총괄·긴급복지지원을 담당한다 — **제주시와의 구조적 차이**: 제주시는 기초생활보장과가 별도 과로 분리돼 있으나(SP-CITYDIV-JEJUSI-WELFARE-BASICLIVELIHOOD), 서귀포시 city-dept-master-data.json에는 별도 기초생활보장과가 없어",
    kw: ["긴급복지지원", "복지 총괄", "주민복지", "주민복지과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-WELFARE-RESIDENT_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-WELFARE-WOMENFAMILY", 국코드: "welfare", 시코드: "seogwipo",
    name: "서귀포시청 복지위생국 여성가족과", desc: "당신은 **서귀포시청 복지위생국 여성가족과**를 대표하는 AI 레이어다. 한부모가족 지원, 가정폭력·성폭력 피해자 보호를 담당한다.",
    kw: ["가정폭력", "성폭력 피해자 보호", "여성가족", "여성가족과", "한부모가족 지원"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-WELFARE-WOMENFAMILY_v1.0.md" },
];

export const DO_DEPT_DIVISION_TABLE = [
  { code: "SP-DIV-INNOV-DIGITAL", domain: "innov",
    name: "혁신산업국 디지털혁신과", desc: "당신은 **제주도청 혁신산업국 디지털혁신과**를 대표하는 AI 레이어다.",
    kw: ["디지털혁신", "디지털혁신과"], file: "02-do-dept/divisions/SP-DIV-INNOV-DIGITAL_v1.0.md" },
  { code: "SP-DIV-INNOV-ENERGYINDUSTRY", domain: "innov",
    name: "혁신산업국 에너지산업과", desc: "당신은 **제주도청 혁신산업국 에너지산업과**(조직개편 확정 시 신설 \"기후에너지국\"으로 이관 예정)를 대표하는 AI 레이어다.",
    kw: ["에너지산업", "에너지산업과"], file: "02-do-dept/divisions/SP-DIV-INNOV-ENERGYINDUSTRY_v1.0.md" },
  { code: "SP-DIV-INNOV-FUTUREGROWTH", domain: "innov",
    name: "혁신산업국 미래성장과", desc: "당신은 **제주도청 혁신산업국**(개칭 예정: 미래산업국) **미래성장과**를 대표하는 AI 레이어다.",
    kw: ["미래성장", "미래성장과"], file: "02-do-dept/divisions/SP-DIV-INNOV-FUTUREGROWTH_v1.0.md" },
  { code: "SP-DIV-INNOV-SPACEMOBILITY", domain: "innov",
    name: "혁신산업국 우주모빌리티과", desc: "당신은 **제주도청 혁신산업국 우주모빌리티과**를 대표하는 AI 레이어다.",
    kw: ["우주모빌리티", "우주모빌리티과"], file: "02-do-dept/divisions/SP-DIV-INNOV-SPACEMOBILITY_v1.0.md" },
  { code: "SP-DIV-JACHI-43SUPPORT", domain: "jachi",
    name: "특별자치행정국 4·3지원과", desc: "당신은 **제주도청 특별자치행정국 4·3지원과**를 대표하는 AI 레이어다. 이 과는 정책 총괄이 아니라 **실제 보상금 접수 창구(도외·해외 거주자용)를 겸한다** — 다른 대부분의 도청 실·국 과와 달리 처분성이 상대적으로 강한 업무를 수행한다.",
    kw: ["4·3지원", "4·3지원과"], file: "02-do-dept/divisions/SP-DIV-JACHI-43SUPPORT_v1.0.md" },
  { code: "SP-DIV-JACHI-ACCOUNTING", domain: "jachi",
    name: "특별자치행정국 회계재산관리과", desc: "당신은 **제주도청 특별자치행정국 회계재산관리과**를 대표하는 AI 레이어다.",
    kw: ["회계재산관리", "회계재산관리과"], file: "02-do-dept/divisions/SP-DIV-JACHI-ACCOUNTING_v1.0.md" },
  { code: "SP-DIV-JACHI-GENERAL", domain: "jachi",
    name: "특별자치행정국 총무과", desc: "당신은 **제주도청 특별자치행정국 총무과**를 대표하는 AI 레이어다. 이 과는 도민을 직접 상대하기보다 도청 내부 행정(문서·인사·의전)을 지원하는 성격이 강하다.",
    kw: ["총무", "총무과"], file: "02-do-dept/divisions/SP-DIV-JACHI-GENERAL_v1.0.md" },
  { code: "SP-DIV-JACHI-SELFGOV", domain: "jachi",
    name: "특별자치행정국 자치행정과", desc: "당신은 **제주도청 특별자치행정국 자치행정과**를 대표하는 AI 레이어다.",
    kw: ["자치행정", "자치행정과"], file: "02-do-dept/divisions/SP-DIV-JACHI-SELFGOV_v1.0.md" },
  { code: "SP-DIV-PLAN-BUDGET", domain: "plan",
    name: "기획조정실 예산담당관", desc: "당신은 **제주도청 기획조정실 예산담당관**을 대표하는 AI 레이어다.",
    kw: ["예산", "예산담당관"], file: "02-do-dept/divisions/SP-DIV-PLAN-BUDGET_v1.0.md" },
  { code: "SP-DIV-PLAN-LEGAL", domain: "plan",
    name: "기획조정실 특별자치법무담당관", desc: "당신은 **제주도청 기획조정실 특별자치법무담당관**을 대표하는 AI 레이어다.",
    kw: ["특별자치법무", "특별자치법무담당관"], file: "02-do-dept/divisions/SP-DIV-PLAN-LEGAL_v1.0.md" },
  { code: "SP-DIV-PLAN-POLICY", domain: "plan",
    name: "기획조정실 정책기획관", desc: "당신은 **제주도청 기획조정실 정책기획관**을 대표하는 AI 레이어다.",
    kw: ["정책기획관"], file: "02-do-dept/divisions/SP-DIV-PLAN-POLICY_v1.0.md" },
  { code: "SP-DIV-PLAN-POPULATION", domain: "plan",
    name: "기획조정실 인구정책담당관", desc: "당신은 **제주도청 기획조정실 인구정책담당관**을 대표하는 AI 레이어다.",
    kw: ["인구정책", "인구정책담당관"], file: "02-do-dept/divisions/SP-DIV-PLAN-POPULATION_v1.0.md" },
  { code: "SP-DIV-PLAN-TAXADMIN", domain: "plan",
    name: "기획조정실 세정담당관", desc: "당신은 **제주도청 기획조정실 세정담당관**을 대표하는 AI 레이어다.",
    kw: ["세정", "세정담당관"], file: "02-do-dept/divisions/SP-DIV-PLAN-TAXADMIN_v1.0.md" },
  { code: "SP-DIV-PLAN-YOUTH", domain: "plan",
    name: "기획조정실 청년정책담당관", desc: "당신은 **제주도청 기획조정실 청년정책담당관**을 대표하는 AI 레이어다.",
    kw: ["청년정책", "청년정책담당관"], file: "02-do-dept/divisions/SP-DIV-PLAN-YOUTH_v1.0.md" },
  { code: "SP-DIV-SAFETY-HEALTHHYGIENE", domain: "safety",
    name: "도민안전건강실 건강위생과", desc: "당신은 **제주도청 도민안전건강실 건강위생과**를 대표하는 AI 레이어다.",
    kw: ["건강위생", "건강위생과"], file: "02-do-dept/divisions/SP-DIV-SAFETY-HEALTHHYGIENE_v1.0.md" },
  { code: "SP-DIV-SAFETY-HEALTHPOLICY", domain: "safety",
    name: "도민안전건강실 보건정책과", desc: "당신은 **제주도청 도민안전건강실 보건정책과**를 대표하는 AI 레이어다.",
    kw: ["보건정책", "보건정책과"], file: "02-do-dept/divisions/SP-DIV-SAFETY-HEALTHPOLICY_v1.0.md" },
  { code: "SP-DIV-SAFETY-NATURALDISASTER", domain: "safety",
    name: "도민안전건강실 자연재난과", desc: "당신은 **제주도청 도민안전건강실 자연재난과**를 대표하는 AI 레이어다.",
    kw: ["자연재난", "자연재난과"], file: "02-do-dept/divisions/SP-DIV-SAFETY-NATURALDISASTER_v1.0.md" },
  { code: "SP-DIV-SAFETY-POLICY", domain: "safety",
    name: "도민안전건강실 안전정책과", desc: "당신은 **제주도청 도민안전건강실 안전정책과**를 대표하는 AI 레이어다.",
    kw: ["안전정책", "안전정책과"], file: "02-do-dept/divisions/SP-DIV-SAFETY-POLICY_v1.0.md" },
  { code: "SP-DIV-SAFETY-SOCIALDISASTER", domain: "safety",
    name: "도민안전건강실 사회재난과", desc: "당신은 **제주도청 도민안전건강실 사회재난과**를 대표하는 AI 레이어다.",
    kw: ["사회재난", "사회재난과"], file: "02-do-dept/divisions/SP-DIV-SAFETY-SOCIALDISASTER_v1.0.md" },
  { code: "SP-DIV-WELFARE-CHILDCARE", domain: "welfare",
    name: "복지가족국 아동보육청소년과", desc: "당신은 **제주도청 복지가족국 아동보육청소년과**를 대표하는 AI 레이어다.",
    kw: ["아동보육청소년", "아동보육청소년과"], file: "02-do-dept/divisions/SP-DIV-WELFARE-CHILDCARE_v1.0.md" },
  { code: "SP-DIV-WELFARE-DISABLED", domain: "welfare",
    name: "복지가족국 장애인복지과", desc: "당신은 **제주도청 복지가족국 장애인복지과**를 대표하는 AI 레이어다.",
    kw: ["장애인복지", "장애인복지과"], file: "02-do-dept/divisions/SP-DIV-WELFARE-DISABLED_v1.0.md" },
  { code: "SP-DIV-WELFARE-ELDERLY", domain: "welfare",
    name: "복지가족국 노인복지과", desc: "당신은 **제주도청 복지가족국 노인복지과**를 대표하는 AI 레이어다.",
    kw: ["노인복지", "노인복지과"], file: "02-do-dept/divisions/SP-DIV-WELFARE-ELDERLY_v1.0.md" },
  { code: "SP-DIV-WELFARE-POLICY", domain: "welfare",
    name: "복지가족국 복지정책과", desc: "당신은 **제주도청 복지가족국 복지정책과**를 대표하는 AI 레이어다.",
    kw: ["복지정책", "복지정책과"], file: "02-do-dept/divisions/SP-DIV-WELFARE-POLICY_v1.0.md" },
];
